#!/usr/bin/env python3
"""
.ai-sync/ Sync Script — Generates platform-specific config files from shared source.

Usage:
    python3 .ai-sync/sync.py              # Generate all platform configs
    python3 .ai-sync/sync.py --check       # Check if configs are up to date
    python3 .ai-sync/sync.py --dry-run     # Preview what would be generated

Generated files (DO NOT EDIT directly — edit .ai-sync/ files instead):
    - AGENTS.md                          (for OpenCode / GLM-5.1)
    - .agents/rules/*.md                 (for Antigravity / Gemini)
    - .agents/workflows/*.md             (copied from .ai-sync/workflows/)

Architecture (per Antigravity official docs + empirical validation):
    - Antigravity defaults to .agents/rules/ (backward support for .agent/rules/)
    - .agents/skills/ is the universal skills folder for both platforms
    - Global rules for Antigravity live in ~/.gemini/GEMINI.md (not managed here)
"""

import hashlib
import shutil
import sys
from pathlib import Path

SYNC_DIR = Path(__file__).parent.resolve()
PROJECT_ROOT = SYNC_DIR.parent

CONTEXT_FILE = SYNC_DIR / "CONTEXT.md"
RULES_FILE = SYNC_DIR / "RULES.md"
OPENCODE_EXT = SYNC_DIR / "extensions" / "opencode.md"
ANTIGRAVITY_EXT = SYNC_DIR / "extensions" / "antigravity.md"
ANTIGRAVITY_PERMS = SYNC_DIR / "extensions" / "antigravity-permissions.yml"
WORKFLOWS_DIR = SYNC_DIR / "workflows"

AGENTS_MD = PROJECT_ROOT / "AGENTS.md"
AGENTS_DIR = PROJECT_ROOT / ".agents"
AGENTS_RULES_DIR = AGENTS_DIR / "rules"
AGENTS_WORKFLOWS_DIR = AGENTS_DIR / "workflows"
AGENTS_RULES_SHARED = AGENTS_RULES_DIR / "project-rules.md"
AGENTS_RULES_PLATFORM = AGENTS_RULES_DIR / "platform-antigravity.md"

AUTOGEN_HEADER = "<!-- AUTO-GENERATED by .ai-sync/sync.py — DO NOT EDIT DIRECTLY -->\n<!-- Edit files in .ai-sync/ instead, then run: python3 .ai-sync/sync.py -->\n\n"

ANTIGRAVITY_CHAR_LIMIT = 12000


def read_file(path: Path) -> str:
    """Read file content, return empty string if not found."""
    if not path.exists():
        print(f"⚠️  Warning: {path.name} not found, skipping", file=sys.stderr)
        return ""
    return path.read_text(encoding="utf-8")


def file_hash(content: str) -> str:
    """Compute SHA256 hash of content for change detection."""
    return hashlib.sha256(content.encode("utf-8")).hexdigest()[:16]


def extract_body(content: str) -> str:
    """Extract body content after the header comment block (before first ## section).

    Header format in .ai-sync/ files:
        # Title
        <blank line>
        > comment lines...
        <blank line>
        ---
        <blank line>
        ## First Real Section

    We skip everything from the first '#' line up to and including the first '---'.
    """
    lines = content.split("\n")
    seen_separator = False
    body_lines = []

    for line in lines:
        if not seen_separator:
            if line.strip() == "---":
                seen_separator = True
            continue
        body_lines.append(line)

    result = "\n".join(body_lines).strip()
    if not seen_separator and content.strip():
        print(
            f"⚠️  Warning: No '---' separator found in source file. "
            f"Entire content will be included. Add a '---' after the header.",
            file=sys.stderr,
        )
        return content.strip()
    return result


def generate_agents_md() -> str:
    """Generate AGENTS.md — unified rules for both OpenCode + Antigravity.

    Both platforms auto-load AGENTS.md from project root. Platform-specific
    extensions are labeled '(OpenCode Only)' / '(Antigravity Only)' so each
    LLM filters via natural language.
    """
    parts = [
        AUTOGEN_HEADER,
        "# AGENTS.md — Auto-loaded rules for AI sessions\n",
    ]

    context = read_file(CONTEXT_FILE)
    if context:
        parts.append(extract_body(context))

    rules = read_file(RULES_FILE)
    if rules:
        parts.append(extract_body(rules))

    opencode_ext = read_file(OPENCODE_EXT)
    if opencode_ext:
        parts.append(extract_body(opencode_ext))

    antigravity_ext = read_file(ANTIGRAVITY_EXT)
    if antigravity_ext:
        parts.append(extract_body(antigravity_ext))

    return "\n\n".join(p for p in parts if p.strip())


def generate_antigravity_platform() -> str:
    """Generate .agents/rules/platform-antigravity.md — permissions frontmatter only.

    Antigravity parses YAML frontmatter for permission enforcement. Markdown
    body is ignored — rules live in AGENTS.md (auto-loaded by both platforms).
    """
    perms = read_file(ANTIGRAVITY_PERMS)
    # Strip comment lines (start with #) and blank lines from the YAML body
    # so we keep only the `permissions:` block for the frontmatter.
    frontmatter = ""
    if perms:
        perm_lines = [
            line for line in perms.splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        ]
        if perm_lines:
            frontmatter = "---\n" + "\n".join(perm_lines) + "\n---\n\n"

    parts = [
        "# Antigravity Permissions\n",
        "> Permissions config for Google Antigravity. Markdown rules live in AGENTS.md.\n",
    ]

    body = "\n\n".join(p for p in parts if p.strip())
    # YAML frontmatter MUST be at line 1 (before any HTML comments) so
    # Antigravity recognizes and enforces the permissions declarations.
    return frontmatter + AUTOGEN_HEADER + body


def sync_workflows(dry_run: bool = False) -> tuple[list[str], int]:
    """Copy .ai-sync/workflows/ to .agents/workflows/.

    Returns (synced_names, error_count) so caller can exit non-zero on overflow.
    """
    synced = []
    errors = 0
    AGENTS_WORKFLOWS_DIR.mkdir(parents=True, exist_ok=True)

    if not WORKFLOWS_DIR.exists():
        return synced, errors

    for workflow_file in WORKFLOWS_DIR.glob("*.md"):
        target = AGENTS_WORKFLOWS_DIR / workflow_file.name
        source_content = workflow_file.read_text(encoding="utf-8")

        # Check char limit first
        if len(source_content) > ANTIGRAVITY_CHAR_LIMIT:
            print(
                f"  ❌ ERROR: {workflow_file.name} is {len(source_content)} chars — exceeds {ANTIGRAVITY_CHAR_LIMIT} char limit!"
            )
            errors += 1
            continue

        # Skip if target already identical (works for both dry-run and real run)
        if target.exists():
            existing = target.read_text(encoding="utf-8")
            if file_hash(source_content) == file_hash(existing):
                if dry_run:
                    print(f"  Up to date: {workflow_file.name}")
                continue

        if dry_run:
            print(f"  Would copy: {workflow_file.name}")
            synced.append(workflow_file.name)
            continue

        shutil.copy2(workflow_file, target)
        synced.append(workflow_file.name)

    return synced, errors


def write_output(path: Path, content: str, dry_run: bool = False, char_limit: int = 0) -> bool:
    """Write content to file. Returns True if file changed."""
    if char_limit and len(content) > char_limit:
        print(
            f"  ❌ ERROR: {path.relative_to(PROJECT_ROOT)} is {len(content)} chars — exceeds {char_limit} char limit!"
        )
        return False

    if dry_run:
        existing = read_file(path) if path.exists() else ""
        if file_hash(content) != file_hash(existing):
            print(f"  Would update: {path.relative_to(PROJECT_ROOT)}")
            return True
        else:
            print(f"  Up to date: {path.relative_to(PROJECT_ROOT)}")
            return False

    existing = read_file(path) if path.exists() else ""
    if file_hash(content) == file_hash(existing):
        return False

    path.write_text(content, encoding="utf-8")
    return True


def check_up_to_date() -> bool:
    """Check if generated files match source files. Returns True if up to date.

    Also validates Antigravity char limit so over-limit files committed directly
    to the repo cannot bypass CI.
    """
    agents_content = generate_agents_md()
    platform_content = generate_antigravity_platform()

    all_ok = True

    def _check_limit(path: Path, content: str) -> None:
        nonlocal all_ok
        if len(content) > ANTIGRAVITY_CHAR_LIMIT:
            print(
                f"❌ {path.relative_to(PROJECT_ROOT)} is {len(content)} chars — exceeds {ANTIGRAVITY_CHAR_LIMIT} char limit!"
            )
            all_ok = False

    # Validate char limits first (catch over-limit even if file matches hash)
    _check_limit(AGENTS_RULES_PLATFORM, platform_content)

    # Migration: legacy project-rules.md should not exist (warn if it does)
    if AGENTS_RULES_SHARED.exists():
        print("⚠️  .agents/rules/project-rules.md is legacy (redundant with AGENTS.md) — run: python3 .ai-sync/sync.py to remove")
        all_ok = False

    if AGENTS_MD.exists():
        existing = read_file(AGENTS_MD)
        if file_hash(agents_content) != file_hash(existing):
            print("❌ AGENTS.md is OUT OF DATE — run: python3 .ai-sync/sync.py")
            all_ok = False
        else:
            print("✅ AGENTS.md is up to date")
    else:
        print("❌ AGENTS.md does not exist — run: python3 .ai-sync/sync.py")
        all_ok = False

    if AGENTS_RULES_PLATFORM.exists():
        existing = read_file(AGENTS_RULES_PLATFORM)
        if file_hash(platform_content) != file_hash(existing):
            print("❌ .agents/rules/platform-antigravity.md is OUT OF DATE — run: python3 .ai-sync/sync.py")
            all_ok = False
        else:
            print("✅ .agents/rules/platform-antigravity.md is up to date")
    else:
        print("❌ .agents/rules/platform-antigravity.md does not exist — run: python3 .ai-sync/sync.py")
        all_ok = False

    if WORKFLOWS_DIR.exists():
        for workflow_file in sorted(WORKFLOWS_DIR.glob("*.md")):
            source_content = workflow_file.read_text(encoding="utf-8")
            if len(source_content) > ANTIGRAVITY_CHAR_LIMIT:
                print(
                    f"❌ .ai-sync/workflows/{workflow_file.name} is {len(source_content)} chars — exceeds {ANTIGRAVITY_CHAR_LIMIT} char limit!"
                )
                all_ok = False
            target = AGENTS_WORKFLOWS_DIR / workflow_file.name
            if not target.exists():
                print(f"❌ .agents/workflows/{workflow_file.name} does not exist — run: python3 .ai-sync/sync.py")
                all_ok = False
            else:
                target_content = target.read_text(encoding="utf-8")
                if file_hash(source_content) != file_hash(target_content):
                    print(f"❌ .agents/workflows/{workflow_file.name} is OUT OF DATE — run: python3 .ai-sync/sync.py")
                    all_ok = False
                else:
                    print(f"✅ .agents/workflows/{workflow_file.name} is up to date")

    return all_ok


def main():
    args = sys.argv[1:]
    dry_run = "--dry-run" in args
    check_only = "--check" in args
    errors = 0

    if check_only:
        print("Checking if generated files are up to date...\n")
        up_to_date = check_up_to_date()
        sys.exit(0 if up_to_date else 1)

    print("🔄 Syncing .ai-sync/ → platform configs...\n")

    if dry_run:
        print("📋 DRY RUN — no files will be modified\n")

    def _emit(path: Path, changed: bool, overflow: bool) -> None:
        """Print status for a generated file. Distinguishes overflow from no-change."""
        nonlocal errors
        if overflow:
            errors += 1
            return  # write_output already printed the ERROR
        if dry_run:
            return  # dry-run path handled inside write_output
        if changed:
            print(f"    ✅ Updated: {path.relative_to(PROJECT_ROOT)}")
        else:
            print(f"    ⏭️  No changes: {path.relative_to(PROJECT_ROOT)}")

    print("Generating AGENTS.md (unified for OpenCode + Antigravity)...")
    agents_content = generate_agents_md()
    changed = write_output(AGENTS_MD, agents_content, dry_run)
    if changed and not dry_run:
        print(f"  ✅ Updated: {AGENTS_MD.relative_to(PROJECT_ROOT)}")
    elif not changed and not dry_run:
        print(f"  ⏭️  No changes: {AGENTS_MD.relative_to(PROJECT_ROOT)}")

    print("\nGenerating .agents/rules/ (Antigravity permissions only)...")
    AGENTS_RULES_DIR.mkdir(parents=True, exist_ok=True)

    print("  Platform permissions (platform-antigravity.md)...")
    platform_content = generate_antigravity_platform()
    platform_overflow = len(platform_content) > ANTIGRAVITY_CHAR_LIMIT
    changed = write_output(AGENTS_RULES_PLATFORM, platform_content, dry_run, char_limit=ANTIGRAVITY_CHAR_LIMIT)
    _emit(AGENTS_RULES_PLATFORM, changed, platform_overflow)

    # Migration: remove legacy project-rules.md (redundant with AGENTS.md)
    if AGENTS_RULES_SHARED.exists():
        if dry_run:
            print("  🗑️  Would remove legacy .agents/rules/project-rules.md (redundant with AGENTS.md)")
        else:
            try:
                AGENTS_RULES_SHARED.unlink(missing_ok=True)
                print("  🧹 Removed legacy .agents/rules/project-rules.md (redundant with AGENTS.md)")
            except OSError as exc:
                print(f"  ⚠️  Could not remove legacy project-rules.md: {exc}", file=sys.stderr)

    print("\nSyncing workflows...")
    synced, wf_errors = sync_workflows(dry_run)
    errors += wf_errors
    if wf_errors:
        print(f"  ❌ {wf_errors} workflow(s) exceeded char limit — not copied")
    if synced and not dry_run:
        print(f"  ✅ Copied {len(synced)} workflows: {', '.join(synced)}")
    elif dry_run and synced:
        print(f"  Would copy {len(synced)} workflows")
    elif not wf_errors:
        print("  ⏭️  No workflows to sync")

    if errors:
        print(f"\n❌ Sync FAILED with {errors} error(s). Generated files may be stale — fix source and re-run.")
        sys.exit(1)

    print(f"\n{'📋 DRY RUN complete' if dry_run else '✅ Sync complete'}!")
    if not dry_run:
        print("  AGENTS.md → OpenCode + Antigravity auto-load this file")
        print("  .agents/rules/platform-antigravity.md → Antigravity permissions frontmatter")
        print("  .agents/workflows/ → Copied from .ai-sync/workflows/")
        print("  .agents/skills/ → Universal skills (managed separately)")
        print("\n⚠️  Remember: NEVER edit generated files directly. Edit .ai-sync/ files instead.")


if __name__ == "__main__":
    main()
